# Generated by Django 2.1.5 on 2019-02-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190213_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_invoice',
            name='invoice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
