# Generated by Django 2.1.5 on 2019-02-14 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_p_invoice_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_invoice',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_musician', to='core.P_Invoice'),
        ),
    ]
