# Generated by Django 2.1.5 on 2019-02-14 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190214_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_invoice',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='core.P_Invoice'),
        ),
    ]
