# Generated by Django 2.1.5 on 2019-02-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data', models.CharField(max_length=255)),
            ],
        ),
    ]
