# Generated by Django 2.1.5 on 2019-02-26 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_customerschart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomersChart',
            new_name='CustomersYearChart',
        ),
        migrations.RenameModel(
            old_name='Test',
            new_name='DateChart',
        ),
    ]
